DROP TABLE IF EXISTS CUSTOMERS; 

CREATE TABLE CUSTOMERS (
    customer_id INT PRIMARY KEY,
    full_name VARCHAR(100),
    email VARCHAR(100) NOT NULL,
    age INT,
    
    CONSTRAINT unique_email UNIQUE (email),
    CONSTRAINT check_age CHECK (age > 0)
);

ALTER TABLE CUSTOMERS 
MODIFY email VARCHAR(100) NOT NULL;

ALTER TABLE CUSTOMERS 
ADD CONSTRAINT check_age CHECK (age > 0);

SELECT * FROM CUSTOMERS;